// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1822:El miembro Get no tiene acceso a los datos de la instancia y se puede marcar como static (Shared en Visual Basic).", Justification = "<pendiente>", Scope = "member", Target = "~M:EVSoft.WebApi.ConsultSIS.Controllers.SISAfiliacionController.Get(System.String,System.String)~System.Threading.Tasks.Task{System.Collections.Generic.IEnumerable{EVSoft.Dominio.ConsultSIS.Entities.AfiliadoResumenEntity}}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA2000:Llame a System.IDisposable.Dispose en el objeto que \"new WSISAfiliacion.AfiliadoSisServiceClient()\" ha creado antes de que todas las referencias a él estén fuera de ámbito.", Justification = "<pendiente>", Scope = "member", Target = "~M:EVSoft.WebApi.ConsultSIS.Controllers.SISAfiliacionController.Get(System.String,System.String)~System.Threading.Tasks.Task{System.Collections.Generic.IEnumerable{EVSoft.Dominio.ConsultSIS.Entities.AfiliadoResumenEntity}}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1822:El miembro Configure no tiene acceso a los datos de la instancia y se puede marcar como static (Shared en Visual Basic).", Justification = "<pendiente>", Scope = "member", Target = "~M:EVSoft.WebApi.ConsultSIS.Startup.Configure(Microsoft.AspNetCore.Builder.IApplicationBuilder,Microsoft.AspNetCore.Hosting.IWebHostEnvironment)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1822:El miembro ConfigureServices no tiene acceso a los datos de la instancia y se puede marcar como static (Shared en Visual Basic).", Justification = "<pendiente>", Scope = "member", Target = "~M:EVSoft.WebApi.ConsultSIS.Startup.ConfigureServices(Microsoft.Extensions.DependencyInjection.IServiceCollection)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1052:“Program” es un tipo contenedor estático, pero no es static ni NotInheritable", Justification = "<pendiente>", Scope = "type", Target = "~T:EVSoft.WebApi.ConsultSIS.Program")]