//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSISAfiliacion
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="afiliadoSisResponseType", Namespace="http://pidesalud.minsa.gob.pe/ws/AfiliadoSisService/", ItemName="afiliadoDetalle")]
    public class afiliadoSisResponseType : System.Collections.Generic.List<WSISAfiliacion.afiliadoType>
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="afiliadoType", Namespace="http://pidesalud.minsa.gob.pe/ws/AfiliadoSisService/")]
    public partial class afiliadoType : object
    {
        
        private string nuAfiliacionField;
        
        private string tiDocumentoField;
        
        private string nuDocumentoField;
        
        private string apPaternoField;
        
        private string apMaternoField;
        
        private string deNombresField;
        
        private string deEstadoField;
        
        private string nuErrorField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string nuAfiliacion
        {
            get
            {
                return this.nuAfiliacionField;
            }
            set
            {
                this.nuAfiliacionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string tiDocumento
        {
            get
            {
                return this.tiDocumentoField;
            }
            set
            {
                this.tiDocumentoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=2)]
        public string nuDocumento
        {
            get
            {
                return this.nuDocumentoField;
            }
            set
            {
                this.nuDocumentoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=3)]
        public string apPaterno
        {
            get
            {
                return this.apPaternoField;
            }
            set
            {
                this.apPaternoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=4)]
        public string apMaterno
        {
            get
            {
                return this.apMaternoField;
            }
            set
            {
                this.apMaternoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=5)]
        public string deNombres
        {
            get
            {
                return this.deNombresField;
            }
            set
            {
                this.deNombresField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=6)]
        public string deEstado
        {
            get
            {
                return this.deEstadoField;
            }
            set
            {
                this.deEstadoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=7)]
        public string nuError
        {
            get
            {
                return this.nuErrorField;
            }
            set
            {
                this.nuErrorField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="afiliadoSisRequestType", Namespace="http://pidesalud.minsa.gob.pe/ws/AfiliadoSisService/")]
    public partial class afiliadoSisRequestType : object
    {
        
        private string tiDocumentoField;
        
        private string nuDocumentoField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string tiDocumento
        {
            get
            {
                return this.tiDocumentoField;
            }
            set
            {
                this.tiDocumentoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=1)]
        public string nuDocumento
        {
            get
            {
                return this.nuDocumentoField;
            }
            set
            {
                this.nuDocumentoField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://pidesalud.minsa.gob.pe/ws/AfiliadoSisService/", ConfigurationName="WSISAfiliacion.AfiliadoSisService")]
    public interface AfiliadoSisService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pidesalud.minsa.gob.pe/ws/AfiliadoSisService/afiliadoSis", ReplyAction="*")]
        System.Threading.Tasks.Task<WSISAfiliacion.afiliadoSisResponse> afiliadoSisAsync(WSISAfiliacion.afiliadoSis request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class afiliadoSis
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="afiliadoSis", Namespace="http://pidesalud.minsa.gob.pe/ws/AfiliadoSisService/", Order=0)]
        public WSISAfiliacion.afiliadoSisRequestType afiliadoSis1;
        
        public afiliadoSis()
        {
        }
        
        public afiliadoSis(WSISAfiliacion.afiliadoSisRequestType afiliadoSis1)
        {
            this.afiliadoSis1 = afiliadoSis1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class afiliadoSisResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="afiliadoSisResponse", Namespace="http://pidesalud.minsa.gob.pe/ws/AfiliadoSisService/", Order=0)]
        public WSISAfiliacion.afiliadoSisResponseType afiliadoSisResponse1;
        
        public afiliadoSisResponse()
        {
        }
        
        public afiliadoSisResponse(WSISAfiliacion.afiliadoSisResponseType afiliadoSisResponse1)
        {
            this.afiliadoSisResponse1 = afiliadoSisResponse1;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface AfiliadoSisServiceChannel : WSISAfiliacion.AfiliadoSisService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class AfiliadoSisServiceClient : System.ServiceModel.ClientBase<WSISAfiliacion.AfiliadoSisService>, WSISAfiliacion.AfiliadoSisService
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public AfiliadoSisServiceClient() : 
                base(AfiliadoSisServiceClient.GetDefaultBinding(), AfiliadoSisServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.AfiliadoSisServicePort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AfiliadoSisServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(AfiliadoSisServiceClient.GetBindingForEndpoint(endpointConfiguration), AfiliadoSisServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AfiliadoSisServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(AfiliadoSisServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AfiliadoSisServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(AfiliadoSisServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AfiliadoSisServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WSISAfiliacion.afiliadoSisResponse> WSISAfiliacion.AfiliadoSisService.afiliadoSisAsync(WSISAfiliacion.afiliadoSis request)
        {
            return base.Channel.afiliadoSisAsync(request);
        }
        
        public System.Threading.Tasks.Task<WSISAfiliacion.afiliadoSisResponse> afiliadoSisAsync(WSISAfiliacion.afiliadoSisRequestType afiliadoSis1)
        {
            WSISAfiliacion.afiliadoSis inValue = new WSISAfiliacion.afiliadoSis();
            inValue.afiliadoSis1 = afiliadoSis1;
            return ((WSISAfiliacion.AfiliadoSisService)(this)).afiliadoSisAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.AfiliadoSisServicePort))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.AfiliadoSisServicePort))
            {
                return new System.ServiceModel.EndpointAddress("http://dpidesalud.minsa.gob.pe/sis/afiliado/v1.0/afiliado");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return AfiliadoSisServiceClient.GetBindingForEndpoint(EndpointConfiguration.AfiliadoSisServicePort);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return AfiliadoSisServiceClient.GetEndpointAddress(EndpointConfiguration.AfiliadoSisServicePort);
        }
        
        public enum EndpointConfiguration
        {
            
            AfiliadoSisServicePort,
        }
    }
}
