//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSISAfiliacion
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="afiliadoSisResponseType", Namespace="http://pidesalud.minsa.gob.pe/ws/AfiliadoSisService/", ItemName="afiliadoDetalle")]
    public class afiliadoSisResponseType : System.Collections.Generic.List<WSISAfiliacion.afiliadoType>
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="afiliadoType", Namespace="http://pidesalud.minsa.gob.pe/ws/AfiliadoSisService/")]
    public partial class afiliadoType : object
    {
        
        private string codErrorField;
        
        private string resultadoField;
        
        private string tipoDocumentoField;
        
        private string nroDocumentoField;
        
        private string apePaternoField;
        
        private string apeMaternoField;
        
        private string nombresField;
        
        private string fecAfiliacionField;
        
        private string eessField;
        
        private string descEESSField;
        
        private string eessUbigeoField;
        
        private string descEESSUbigeoField;
        
        private string regimenField;
        
        private string tipoSeguroField;
        
        private string descTipoSeguroField;
        
        private string contratoField;
        
        private string fecCaducidadField;
        
        private string estadoField;
        
        private string tablaField;
        
        private string idNumRegField;
        
        private string generoField;
        
        private string fecNacimientoField;
        
        private string idUbigeoField;
        
        private string direccionField;
        
        private string disaField;
        
        private string tipoFormatoField;
        
        private string nroContratoField;
        
        private string correlativoField;
        
        private string idPlanField;
        
        private string idGrupoPoblacionalField;
        
        private string msgConfidencialField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string codError
        {
            get
            {
                return this.codErrorField;
            }
            set
            {
                this.codErrorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string resultado
        {
            get
            {
                return this.resultadoField;
            }
            set
            {
                this.resultadoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string tipoDocumento
        {
            get
            {
                return this.tipoDocumentoField;
            }
            set
            {
                this.tipoDocumentoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=3)]
        public string nroDocumento
        {
            get
            {
                return this.nroDocumentoField;
            }
            set
            {
                this.nroDocumentoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=4)]
        public string apePaterno
        {
            get
            {
                return this.apePaternoField;
            }
            set
            {
                this.apePaternoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=5)]
        public string apeMaterno
        {
            get
            {
                return this.apeMaternoField;
            }
            set
            {
                this.apeMaternoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=6)]
        public string nombres
        {
            get
            {
                return this.nombresField;
            }
            set
            {
                this.nombresField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=7)]
        public string fecAfiliacion
        {
            get
            {
                return this.fecAfiliacionField;
            }
            set
            {
                this.fecAfiliacionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=8)]
        public string eess
        {
            get
            {
                return this.eessField;
            }
            set
            {
                this.eessField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=9)]
        public string descEESS
        {
            get
            {
                return this.descEESSField;
            }
            set
            {
                this.descEESSField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=10)]
        public string eessUbigeo
        {
            get
            {
                return this.eessUbigeoField;
            }
            set
            {
                this.eessUbigeoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=11)]
        public string descEESSUbigeo
        {
            get
            {
                return this.descEESSUbigeoField;
            }
            set
            {
                this.descEESSUbigeoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=12)]
        public string regimen
        {
            get
            {
                return this.regimenField;
            }
            set
            {
                this.regimenField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=13)]
        public string tipoSeguro
        {
            get
            {
                return this.tipoSeguroField;
            }
            set
            {
                this.tipoSeguroField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=14)]
        public string descTipoSeguro
        {
            get
            {
                return this.descTipoSeguroField;
            }
            set
            {
                this.descTipoSeguroField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=15)]
        public string contrato
        {
            get
            {
                return this.contratoField;
            }
            set
            {
                this.contratoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=16)]
        public string fecCaducidad
        {
            get
            {
                return this.fecCaducidadField;
            }
            set
            {
                this.fecCaducidadField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=17)]
        public string estado
        {
            get
            {
                return this.estadoField;
            }
            set
            {
                this.estadoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=18)]
        public string tabla
        {
            get
            {
                return this.tablaField;
            }
            set
            {
                this.tablaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=19)]
        public string idNumReg
        {
            get
            {
                return this.idNumRegField;
            }
            set
            {
                this.idNumRegField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=20)]
        public string genero
        {
            get
            {
                return this.generoField;
            }
            set
            {
                this.generoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=21)]
        public string fecNacimiento
        {
            get
            {
                return this.fecNacimientoField;
            }
            set
            {
                this.fecNacimientoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=22)]
        public string idUbigeo
        {
            get
            {
                return this.idUbigeoField;
            }
            set
            {
                this.idUbigeoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=23)]
        public string direccion
        {
            get
            {
                return this.direccionField;
            }
            set
            {
                this.direccionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=24)]
        public string disa
        {
            get
            {
                return this.disaField;
            }
            set
            {
                this.disaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=25)]
        public string tipoFormato
        {
            get
            {
                return this.tipoFormatoField;
            }
            set
            {
                this.tipoFormatoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=26)]
        public string nroContrato
        {
            get
            {
                return this.nroContratoField;
            }
            set
            {
                this.nroContratoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=27)]
        public string correlativo
        {
            get
            {
                return this.correlativoField;
            }
            set
            {
                this.correlativoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=28)]
        public string idPlan
        {
            get
            {
                return this.idPlanField;
            }
            set
            {
                this.idPlanField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=29)]
        public string idGrupoPoblacional
        {
            get
            {
                return this.idGrupoPoblacionalField;
            }
            set
            {
                this.idGrupoPoblacionalField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=30)]
        public string msgConfidencial
        {
            get
            {
                return this.msgConfidencialField;
            }
            set
            {
                this.msgConfidencialField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="afiliadoSisRequestType", Namespace="http://pidesalud.minsa.gob.pe/ws/AfiliadoSisService/")]
    public partial class afiliadoSisRequestType : object
    {
        
        private string tiDocumentoField;
        
        private string nuDocumentoField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string tiDocumento
        {
            get
            {
                return this.tiDocumentoField;
            }
            set
            {
                this.tiDocumentoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=1)]
        public string nuDocumento
        {
            get
            {
                return this.nuDocumentoField;
            }
            set
            {
                this.nuDocumentoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="afiliadosSisRequestType", Namespace="http://pidesalud.minsa.gob.pe/ws/AfiliadoSisService/")]
    public partial class afiliadosSisRequestType : object
    {
        
        private string usuarioField;
        
        private string passwordField;
        
        private string tiDocumentoField;
        
        private string nuDocumentoField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string usuario
        {
            get
            {
                return this.usuarioField;
            }
            set
            {
                this.usuarioField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=1)]
        public string password
        {
            get
            {
                return this.passwordField;
            }
            set
            {
                this.passwordField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=2)]
        public string tiDocumento
        {
            get
            {
                return this.tiDocumentoField;
            }
            set
            {
                this.tiDocumentoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=3)]
        public string nuDocumento
        {
            get
            {
                return this.nuDocumentoField;
            }
            set
            {
                this.nuDocumentoField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://pidesalud.minsa.gob.pe/ws/AfiliadoSisService/", ConfigurationName="WSISAfiliacion.AfiliadoSisService")]
    public interface AfiliadoSisService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pidesalud.minsa.gob.pe/ws/AfiliadoSisService/afiliadoSis", ReplyAction="*")]
        System.Threading.Tasks.Task<WSISAfiliacion.afiliadoSisResponse> afiliadoSisAsync(WSISAfiliacion.afiliadoSis request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pidesalud.minsa.gob.pe/ws/AfiliadoSisService/afiliadosSis", ReplyAction="*")]
        System.Threading.Tasks.Task<WSISAfiliacion.afiliadosSisResponse> afiliadosSisAsync(WSISAfiliacion.afiliadosSis request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class afiliadoSis
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="afiliadoSis", Namespace="http://pidesalud.minsa.gob.pe/ws/AfiliadoSisService/", Order=0)]
        public WSISAfiliacion.afiliadoSisRequestType afiliadoSis1;
        
        public afiliadoSis()
        {
        }
        
        public afiliadoSis(WSISAfiliacion.afiliadoSisRequestType afiliadoSis1)
        {
            this.afiliadoSis1 = afiliadoSis1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class afiliadoSisResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="afiliadoSisResponse", Namespace="http://pidesalud.minsa.gob.pe/ws/AfiliadoSisService/", Order=0)]
        public WSISAfiliacion.afiliadoSisResponseType afiliadoSisResponse1;
        
        public afiliadoSisResponse()
        {
        }
        
        public afiliadoSisResponse(WSISAfiliacion.afiliadoSisResponseType afiliadoSisResponse1)
        {
            this.afiliadoSisResponse1 = afiliadoSisResponse1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class afiliadosSis
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="afiliadosSis", Namespace="http://pidesalud.minsa.gob.pe/ws/AfiliadoSisService/", Order=0)]
        public WSISAfiliacion.afiliadosSisRequestType afiliadosSis1;
        
        public afiliadosSis()
        {
        }
        
        public afiliadosSis(WSISAfiliacion.afiliadosSisRequestType afiliadosSis1)
        {
            this.afiliadosSis1 = afiliadosSis1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class afiliadosSisResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="afiliadosSisResponse", Namespace="http://pidesalud.minsa.gob.pe/ws/AfiliadoSisService/", Order=0)]
        public WSISAfiliacion.afiliadoSisResponseType afiliadosSisResponse1;
        
        public afiliadosSisResponse()
        {
        }
        
        public afiliadosSisResponse(WSISAfiliacion.afiliadoSisResponseType afiliadosSisResponse1)
        {
            this.afiliadosSisResponse1 = afiliadosSisResponse1;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface AfiliadoSisServiceChannel : WSISAfiliacion.AfiliadoSisService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class AfiliadoSisServiceClient : System.ServiceModel.ClientBase<WSISAfiliacion.AfiliadoSisService>, WSISAfiliacion.AfiliadoSisService
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public AfiliadoSisServiceClient() : 
                base(AfiliadoSisServiceClient.GetDefaultBinding(), AfiliadoSisServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.AfiliadoSisServicePort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AfiliadoSisServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(AfiliadoSisServiceClient.GetBindingForEndpoint(endpointConfiguration), AfiliadoSisServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AfiliadoSisServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(AfiliadoSisServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AfiliadoSisServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(AfiliadoSisServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AfiliadoSisServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WSISAfiliacion.afiliadoSisResponse> WSISAfiliacion.AfiliadoSisService.afiliadoSisAsync(WSISAfiliacion.afiliadoSis request)
        {
            return base.Channel.afiliadoSisAsync(request);
        }
        
        public System.Threading.Tasks.Task<WSISAfiliacion.afiliadoSisResponse> afiliadoSisAsync(WSISAfiliacion.afiliadoSisRequestType afiliadoSis1)
        {
            WSISAfiliacion.afiliadoSis inValue = new WSISAfiliacion.afiliadoSis();
            inValue.afiliadoSis1 = afiliadoSis1;
            return ((WSISAfiliacion.AfiliadoSisService)(this)).afiliadoSisAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WSISAfiliacion.afiliadosSisResponse> WSISAfiliacion.AfiliadoSisService.afiliadosSisAsync(WSISAfiliacion.afiliadosSis request)
        {
            return base.Channel.afiliadosSisAsync(request);
        }
        
        public System.Threading.Tasks.Task<WSISAfiliacion.afiliadosSisResponse> afiliadosSisAsync(WSISAfiliacion.afiliadosSisRequestType afiliadosSis1)
        {
            WSISAfiliacion.afiliadosSis inValue = new WSISAfiliacion.afiliadosSis();
            inValue.afiliadosSis1 = afiliadosSis1;
            return ((WSISAfiliacion.AfiliadoSisService)(this)).afiliadosSisAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.AfiliadoSisServicePort))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.AfiliadoSisServicePort))
            {
                return new System.ServiceModel.EndpointAddress("http://dpidesalud.minsa.gob.pe/sis/afiliado/v1.0/afiliado");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return AfiliadoSisServiceClient.GetBindingForEndpoint(EndpointConfiguration.AfiliadoSisServicePort);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return AfiliadoSisServiceClient.GetEndpointAddress(EndpointConfiguration.AfiliadoSisServicePort);
        }
        
        public enum EndpointConfiguration
        {
            
            AfiliadoSisServicePort,
        }
    }
}
